# Generated by Django 5.2.3 on 2025-07-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether this user has been approved by an admin.'),
        ),
    ]
