# Generated by Django 5.2.3 on 2025-07-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='availability',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('office_material', 'Office Material'), ('gardening_supplies', 'Gardening Supplies'), ('physical_space', 'Physical Space'), ('tools', 'Tools'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='dimensions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='qty',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
