# Generated by Django 5.2.3 on 2025-07-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_listing_image_listingimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('office_material', 'Office Equipment'), ('outdoors', 'Outdoors'), ('physical_space', 'Physical Space'), ('filming_equipment', 'Filming Equipment'), ('event_equipments', 'Event Equipment'), ('kids', 'Kids'), ('sports_and_games', 'Sports and Games'), ('kitchen_cooking', 'Kitchen / Cooking'), ('art_equipment', 'Art Equipment'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
